apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cards-api
  namespace: cards
spec:
  rules:
    - host: cards.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cards-api
                port:
                  number: 80
